trigger:
- main  # Specify the branch to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Choose an appropriate agent pool and image

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo 'Running build automation'
        npm install
      displayName: 'Build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'dist/trainschedule.zip'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/trainschedule.zip'
        replaceExistingArchive: true
      displayName: 'Archive Artifacts'
      
    - publish: $(Build.ArtifactStagingDirectory)/trainschedule.zip
      artifact: drop
      displayName: 'Publish Artifact'