trigger:
- main  # Specify the branch to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Choose an appropriate agent pool and image

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo 'Running build automation'
        npm install
      displayName: 'Build'

    - script: |
        echo 'Archiving artifacts'
        mkdir -p $(Build.ArtifactStagingDirectory)
        zip -r $(Build.ArtifactStagingDirectory)/trainschedule.zip dist/trainschedule
      displayName: 'Archive Artifacts'
    
      
    - publish: $(Build.ArtifactStagingDirectory)/trainschedule.zip
      artifact: drop
      displayName: 'Publish Artifact'