trigger:
- main  # Specify the branch to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Choose an appropriate agent pool and image

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo 'Running build automation'
        ./gradlew build --no-daemon  --stacktrace
      displayName: 'Build'
      env:
        JAVA_HOME: $(Agent.ToolsDirectory)/usr/lib/jvm/java-11-openjdk-11.0.7.10-1.el8_1.x86_64
      
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'dist/trainschedule.zip'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/trainschedule.zip'
        replaceExistingArchive: true
      displayName: 'Archive Artifacts'
      
    - publish: $(Build.ArtifactStagingDirectory)/trainschedule.zip
      artifact: drop
      displayName: 'Publish Artifact'